### ISSUE TITLE
Adding Numbers to allow list using GUI Fails

### ISSUE THREAD

**Issue by lgaetz** [FreePBX-ContributedModules/allowlist#2]
Testing allowlist ver. 17.0.1

Browse to Allow List and click the button to add a new number. Fill in the name and number fields and click the 'Save Changes' button and nothing happens. The dialog box stays on the screen and the allow list entry is not created.

**Comment by msanthosh18** [comment]
Unable to reproduce the above issue with latest version 17.0.1.1, attached small video which is working for my testing system
[allowlist-adding-17.0.1.1.webm](https://github.com/FreePBX-ContributedModules/allowlist/assets/159993744/a936f62a-7c09-4dce-b80a-90fe1561f6da)
